### ISSUE TITLE
Timeout error with discoverSchema

### ISSUE THREAD

**Issue by cdokolas** [strongloop/loopback-connector-mssql#110]
I'm trying to write a db-to-schema (JSON) generator. After retrieving the desired list of tables (in an array, via `discoverModelDefinitions`), I pass it to a method that calls the datasource's `discoverSchema` method to get the schema through a callback that does just that.

Sample code:

```javascript
var DataSource = require('loopback-datasource-juggler').DataSource;
var ds = new DataSource('dev', {
  // setup the mssql datasource
});

function saveSchema(err, schema) {
  // save the schema to a file
}

function processModelDefs(models) {
  console.log('Processing models...');
  models.forEach((s) => {
    console.log(`Checking ${s.name}`);
    ds.discoverSchema(s.name, {}, saveSchema);
  });
  console.log('Finished processing models.');
}

ds.discoverModelDefinitions({
  owner: 'dbo',
  views: true
}, (err, models) => {
  if (err) {
    console.error(err);
  } else {
    fs.writeFile('./model_definition_dump.json', JSON.stringify(models, null, 2), (err) => {
      if (err) {
        console.log(err);
      } else {
        console.log('discoverModelDefinitions results saved');
      }
    });
    processModelDefs(models);
  }
});
```

After a bunch of successful schema outputs (between 10-20) I get repeated "RequestError: Timeout: Request failed to complete in 15000ms" errors like the following:

```
{ RequestError: Timeout: Request failed to complete in 15000ms
    at Request.userCallback (projectfolder\node_modules\loopback-connector-mssql\node_modules\mssql\lib\tedious.js:802:25)
    at Request.callback (projectfolder\node_modules\loopback-connector-mssql\node_modules\mssql\node_modules\tedious\lib\request.js:33:27)
    at Connection.message (projectfolder\node_modules\loopback-connector-mssql\node_modules\mssql\node_modules\tedious\lib\connection.js:1209:31)
    at Connection.dispatchEvent (projectfolder\node_modules\loopback-connector-mssql\node_modules\mssql\node_modules\tedious\lib\connection.js:519:45)
    at MessageIO.<anonymous> (projectfolder\node_modules\loopback-connector-mssql\node_modules\mssql\node_modules\tedious\lib\connection.js:439:23)
    at emitNone (events.js:86:13)
    at MessageIO.emit (events.js:185:7)
    at ReadablePacketStream.<anonymous> (projectfolder\node_modules\loopback-connector-mssql\node_modules\mssql\node_modules\tedious\lib\message-io.js:92:15)
    at emitOne (events.js:96:13)
    at ReadablePacketStream.emit (events.js:188:7)
    at readableAddChunk (projectfolder\node_modules\loopback-connector-mssql\node_modules\mssql\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:210:18)
    at ReadablePacketStream.Readable.push (projectfolder\node_modules\loopback-connector-mssql\node_modules\mssql\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:169:10)
    at ReadablePacketStream.Transform.push (projectfolder\node_modules\loopback-connector-mssql\node_modules\mssql\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:123:32)
    at ReadablePacketStream._transform (projectfolder\node_modules\loopback-connector-mssql\node_modules\mssql\node_modules\tedious\lib\message-io.js:57:16)
    at ReadablePacketStream.Transform._read (projectfolder\node_modules\loopback-connector-mssql\node_modules\mssql\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at ReadablePacketStream.Transform._write (projectfolder\node_modules\loopback-connector-mssql\node_modules\mssql\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (projectfolder\node_modules\loopback-connector-mssql\node_modules\mssql\node_modules\tedious\node_modules\readable-stream\lib\_stream_writable.js:319:64)
  name: 'RequestError',
  message: 'Timeout: Request failed to complete in 15000ms',
  code: 'ETIMEOUT',
  number: 'ETIMEOUT',
  lineNumber: undefined,
  state: undefined,
  class: undefined,
  serverName: undefined,
  procName: undefined,
  precedingErrors: [] }
```

node.js@6.5.0
loopback@2.36.0
loopback-connector-mssql@2.9.0

**Comment by TiagoCunhaF** [comment]
The default value for mssql connector is 15000, but you can change timeout in your datasources.json like this:
...
    "connector": "mssql",
    "requestTimeout" : 50000

**Comment by dhmlau** [comment]
@cdokolas, does increasing timeout (as suggested by @TiagoCunhaF)  fix your problem?

**Comment by nklt** [comment]
have you tried double checking the connection string (i.e. host name, account and password)? I notice the connector tends to provide a timeout when in some case there is a problem in configuration used. 

also the connector has special requirements if instance name is used, i.e  HOST\SCHEMA. This requires the connection string to have \\ chars in it.

**Comment by cdokolas** [comment]
Sorry folks, I had no time to re-check this :(

**Comment by cdokolas** [comment]
Using a `"requestTimeout" : 50000` did the trick. All 121 items' schemas were saved as JSON files.

Hooray!
