### ISSUE TITLE
Loopback 4 Transaction returning undefined. 

### ISSUE THREAD

**Issue by metkuten** [strongloop/loopback-connector-mssql#218]
@raymondfeng , @bajtos 
I have implemented Repository which is extending DefaultTransactionalRepository.

Issue is, for **.beginTransaction();** getting undefined instead of Promise<Transaction>. function is immediately returning undefined

Using below NPM package
"@loopback/authentication": "2.1.4",
"@loopback/boot": "1.5.5",
"@loopback/context": "1.22.1",
"@loopback/core": "1.10.1",
"@loopback/openapi-v3": "1.9.6",
"@loopback/repository": "1.13.1",
"@loopback/repository-json-schema": "1.9.7",
"loopback-connector-mssql": "^3.3.0",

**And getting below error in console.**
2019-11-15T21:00:52.747Z [founders-mw-dev-699fbb8489-z6k46] error: {"APPLICATION_NAME":"FOUNDERS_SVC","MESSAGE":"uncaughtException: cb is not a function\nTypeError: cb is not a function\n at /u01/foundersplatform/founders-mw/node_modules/loopback-connector/lib/transaction.js:119:5\n at /u01/foundersplatform/founders-mw/node_modules/loopback-connector-mssql/lib/transaction.js:25:7\n at /u01/foundersplatform/founders-mw/node_modules/loopback-connector-mssql/node_modules/mssql/lib/base.js:813:9\n at /u01/foundersplatform/founders-mw/node_modules/loopback-connector-mssql/node_modules/mssql/lib/tedious.js:333:11\n at Request.userCallback (/u01/foundersplatform/founders-mw/node_modules/loopback-connector-mssql/node_modules/tedious/lib/connection.js:1479:16)\n at Request._this.callback (/u01/foundersplatform/founders-mw/node_modules/loopback-connector-mssql/node_modules/tedious/lib/request.js:61:27)\n at Connection.endOfMessageMarkerReceived (/u01/foundersplatform/founders-mw/node_modules/loopback-connector-mssql/node_modules/tedious/lib/connection.js:1944:20)\n at Connection.dispatchEvent (/u01/foundersplatform/founders-mw/node_modules/loopback-connector-mssql/node_modules/tedious/lib/connection.js:1012:38)\n at Parser. (/u01/foundersplatform/founders-mw/node_modules/loopback-connector-mssql/node_modules/tedious/lib/connection.js:812:18)\n at Parser.emit (events.js:209:13)\n at Parser. (/u01/foundersplatform/founders-mw/node_modules/loopback-connector-mssql/node_modules/tedious/lib/token/token-stream-parser.js:54:15)\n at Parser.emit (events.js:209:13)\n at addChunk (/u01/foundersplatform/founders-mw/node_modules/readable-stream/lib/_stream_readable.js:291:12)\n at readableAddChunk (/u01/foundersplatform/founders-mw/node_modules/readable-stream/lib/_stream_readable.js:278:11)\n at Parser.Readable.push (/u01/foundersplatform/founders-mw/node_modules/readable-stream/lib/_stream_readable.js:245:10)\n at Parser.Transform.push (/u01/foundersplatform/founders-mw/node_modules/readable-stream/lib/_stream_transform.js:148:32)"}

Kindly look into this.

**Comment by dhmlau** [comment]
@metkuten, to help us to reproduce the problem, could you please provide a small application and steps to reproduce? Thanks. https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs

**Comment by metkuten** [comment]
@dhmlau : below is the code snapshot, unfortunately i work for a bank and its hard to provide more code details. but i am sure, i am following details provided on loopback4 tutorials(model, transaction repository, passing transaction object into repository call(create),etc). 

all other insert, get quires works perfectly fine. 
code snapshot

1. export class PersonRepository extends DefaultTransactionalRepository

2. controller i have below code. 
async createTransaction(): Promise<Transaction> {
    return this.personRepo.beginTransaction();
  }

**const dbTransactionPromise = this.personsService.createTransaction();
dbTransaction = await dbTransactionPromise;**

**Comment by dhmlau** [comment]
@metkuten, I have the following test code and it seems to be working: 
```
/**
   * Test endpoint
   * @param id
   */
  @get('/customers/create-find/{id}', {
    responses: {
      '200': {
        description: 'Customer model instance',
        content: {'application/json': {schema: getModelSchemaRef(Customer)}},
      },
    },
  })
  async createAndFind(@param.path.string('id') id: string): Promise<Customer> {
    let tx: Transaction;
    tx = await this.customerRepository.beginTransaction(
      IsolationLevel.READ_COMMITTED,
    );
    const newCustomer = await this.customerRepository.create(
      {
        name: 'Bob',
        city: 'Toronto',
      },
      {transaction: tx},
    );
    await tx.commit();
    return this.customerRepository.findById(id);
  }
```

I'm using https://github.com/strongloop/loopback-next/blob/master/packages/repository-tests/src/crud/transactions.suite.ts as reference. Hope it helps.

**Comment by metkuten** [comment]
@dhmlau : as i mentioned above , i am exactly implementing like this. and it's throwing an exception. look like call back "cb" is not working in the code.

**Comment by dhmlau** [comment]
@strongloop/loopback-maintainers, might need your help here.  It seems like @metkuten and I are doing the same thing to call `beginTransaction` (my test code is [here](https://github.com/strongloop/loopback-connector-mssql/issues/218#issuecomment-555824463)), but I wasn't able to reproduce the problem.

**Comment by heroca60** [comment]
Why loopback4 in the transactions retains and does not release the auto incremental id despite using await tx.rollback () when the transaction fails.
My repositories inherit from Default Transactional Repository as indicated in the official documentation
