### ISSUE TITLE
Put request with non existent properties result in error

### ISSUE THREAD

**Issue by erikverheij** [strongloop/loopback-connector-mssql#45]
Put requests having non existent properties (properties that do not exists in the model definition) are resulting in the following error;

    TypeError: Cannot read property 'id' of undefined
        at MySQL.SQLConnector.buildFields (\loopback-connector-mysql\node_modules\loopback-connector\lib\sql.js:861:24)
        at MySQL.SQLConnector.buildFieldsForUpdate (\loopback-connector-mysql\node_modules\loopback-connector\lib\sql.js:892:21)
        at MySQL.SQLConnector.buildUpdate (\loopback-connector-mysql\node_modules\loopback-connector\lib\sql.js:583:21)
        at MySQL.SQLConnector.update (\loopback-connector-mysql\node_modules\loopback-connector\lib\sql.js:601:19)
        at MySQL.SQLConnector.updateAttributes (\loopback-connector-mysql\node_modules\loopback-connector\lib\sql.js:570:8)
        at ModelConstructor.<anonymous> (\loopback-datasource-juggler\lib\dao.js:2253:23)
        at ModelConstructor.trigger (\loopback-datasource-juggler\lib\hooks.js:65:12)
        at ModelConstructor.<anonymous> (\loopback-datasource-juggler\lib\dao.js:2218:14)
        at ModelConstructor.trigger (\loopback-datasource-juggler\lib\hooks.js:65:12)
        at \loopback-datasource-juggler\lib\dao.js:2217:12

The field builder could just skip the property when it is not in the model definition. Perhaps it is even better to remove such properties before it hits the data connector layer?

**Comment by raymondfeng** [comment]
Good catch. I'll fix it.

**Comment by raymondfeng** [comment]
Fixed by loopback-connector@2.1.2

**Comment by erikverheij** [comment]
Thanks for the quick fix!
