### ISSUE TITLE
AuthToken Error "Conversion failed when converting from a character string to uniqueidentifier."

### ISSUE THREAD

**Issue by jaideepdas** [strongloop/loopback-connector-mssql#53]
When i try to use the login API

```
http://localhost:3000/api/Users/login?include=user
```

I am getting the error in the console

```
RequestError: Conversion failed when converting from a character string to uniqueidentifier.
    at Connection.<anonymous> (E:\projects\ssgfluux\node_modules\loopback-connector-mssql\node_modules\mssql\lib\tedious.js:661:17)
    at Connection.emit (events.js:107:17)
    at Parser.<anonymous> (E:\projects\ssgfluux\node_modules\loopback-connector-mssql\node_modules\mssql\node_modules\tedious\lib\connection.js:472:15)
    at Parser.emit (events.js:107:17)
    at Parser.<anonymous> (E:\projects\ssgfluux\node_modules\loopback-connector-mssql\node_modules\mssql\node_modules\tedious\lib\token\token-stream-parser.js:40:24)
    at Parser.emit (events.js:107:17)
    at readableAddChunk (E:\projects\ssgfluux\node_modules\loopback-connector-mssql\node_modules\mssql\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:198:16)
    at Parser.Readable.push (E:\projects\ssgfluux\node_modules\loopback-connector-mssql\node_modules\mssql\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:162:10)
    at Parser.Transform.push (E:\projects\ssgfluux\node_modules\loopback-connector-mssql\node_modules\mssql\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:133:32)
    at Parser.callee$1$0$ (E:\projects\ssgfluux\node_modules\loopback-connector-mssql\node_modules\mssql\node_modules\tedious\lib\token\stream-parser.js:92:18)
```

This is my migration script

```
app.models().forEach(function(Model) {
    app.dataSources.db.automigrate(Model.modelName, function(err) {
      if (err) console.log(err);
    });
  });
```

![accesstoken fields](https://cloud.githubusercontent.com/assets/1322424/9393381/35772ae2-479f-11e5-9a72-8613da3534a4.PNG)
This is the column structure i am seeing in the mssql server manager.

**Comment by jaideepdas** [comment]
Using sql profile this is the query I am seeing which is erroring out.
```
exec sp_executesql @statement=N'SELECT * FROM (SELECT [id],[ttl],[created],[userId],ROW_NUMBER() OVER (ORDER BY [id]) AS RowNum FROM [dbo].[AccessToken] WHERE [id]=N''jWlWuYsAMMvgELBLVTrskk5KyA6DiUPEXxoBDQlBq0RUTvLoaqJDq6wKhPxfE9JD''
) AS S
 WHERE S.RowNum > 0 AND S.RowNum <= 1
```

**Comment by JPorter1214** [comment]
I am having the same issue. Were you able to find a solution?

**Comment by jaideepdas** [comment]
in this grunt task I am running all the SQL queries that I needed to fix this, but the bug I don't think is fixed yet.
```
  grunt.registerTask('mssqlfixes', 'Schema changes for MSSQL', function() {
    var app = require(path.resolve(__dirname, './server/server.js'));
    var dataSource = app.dataSources.db;
    var done = this.async();
    dataSource.once('connected', function() {
      //Drop access token table and recreate
      dataSource.connector.execute('DROP TABLE dbo.AccessToken', [], function(err, res) {
        if (err) {
          console.log('Failed to drop AccessToken table', err.message);
        } else {
          console.log('Dropped AccessToken table successfully');
        }
        dataSource.connector.execute('CREATE TABLE dbo.AccessToken (id nvarchar(255) NOT NULL, ttl int NULL, created datetime NULL, userId int NULL) ON[PRIMARY]', [], function(err, res) {
          if (err) {
            console.log('Failed to create AccessToken table', err.message);
          } else {
            console.log('Created AccessToken table successfully');
            dataSource.connector.execute('ALTER TABLE dbo.AccessToken ADD CONSTRAINT PK_AccessToken PRIMARY KEY CLUSTERED (id) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]', [], function(err, res) {
              if (err) {
                console.log('Failed to create PK_AccessToken constraint', err.message);
              } else {
                console.log('Successfully created PK_AccessToken constraint');
              }
              done();
            });
          }
        });
      });
    });
  });
```

**Comment by sochka** [comment]
any updates on the fix in the repo?

**Comment by a300600st** [comment]
I'm getting the same error. The problem seems to be caused because automigrate is creating the AccessToken table with an id of type uniqueidentifier. Changing the column type to varchar(255) fixes the problem. I'm new to loopback so I can't tell what the origin of this issue is but it seems like the problem is with automigrate.

**Comment by sochka** [comment]
@a300600st you're right about automigrate - same for me. I tried various configurations and didn't find out anything better than manually creating the schema.

**Comment by a300600st** [comment]
@sochka Well this seems like a good chance to get acquainted with writing a loopback-connector. I'll look into it and see what I can figure out. Maybe I can get this fixed.

**Comment by zekizeki** [comment]
I have this issue when using MSSQL too.

**Comment by denkan** [comment]
Same here, using v2.7.1

**Comment by denkan** [comment]
My temporary fix was to add a boot script based on @jaideepdas grunt snippet, but first check the datatype of the id column, and if it's wrong - re-create table with correct datatype:

**/server/boot/mssql-fix.js**
```
module.exports = function(app) {

  //Our mssql datasource
  var db = app.dataSources.mssql1;

  db.once('connected', function() {

    //Check AccessToken.id datatype
    db.connector.execute('SELECT DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=\'AccessToken\' AND COLUMN_NAME=\'id\'', [], function(err, res){
      var idType;
      if(err) {
        console.log('Failed to check AccessToken.id column type', err.message);
      } else {
        idType = res.length ? res[0].DATA_TYPE : null;
        console.log('AccessToken.id type is ' + idType);
      }

      //Id column is already nvarchar - abort!
      if(idType === 'nvarchar') return;

      //Drop access token table and recreate
      db.connector.execute('DROP TABLE dbo.AccessToken', [], function(err, res) {
        if (err) {
          console.log('Failed to drop AccessToken table', err.message);
        } else {
          console.log('Dropped AccessToken table successfully');
        }
        db.connector.execute('CREATE TABLE dbo.AccessToken (id nvarchar(255) NOT NULL, ttl int NULL, created datetime NULL, userId int NULL) ON[PRIMARY]', [], function(err, res) {
          if (err) {
            console.log('Failed to create AccessToken table', err.message);
          } else {
            console.log('Created AccessToken table successfully');
            db.connector.execute('ALTER TABLE dbo.AccessToken ADD CONSTRAINT PK_AccessToken PRIMARY KEY CLUSTERED (id) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]', [], function(err, res) {
              if (err) {
                console.log('Failed to create PK_AccessToken constraint', err.message);
              } else {
                console.log('Successfully created PK_AccessToken constraint');
              }
            });
          }
        });
      });
    });

  });
}
```

**Comment by ataft** [comment]
Any updates on this?

I'm doing something similar to @denkan as a workaround, but it's not pretty. This seems related to issue #71 and partially related to issue #7 too.

**Comment by ajbeach2** [comment]
This is STILL an issue "loopback-connector-mssql": "^3.1.0".

**Comment by robbievandam** [comment]
Fascinating how this lib is **NOT** MIT tbh..

**Comment by Menshawi** [comment]
I have been having the same issue as well with the mssql connector and loopback. To overcome the issue, I added a custom operation hook to my own AccessToken model which has Loopback's AccessToken model as its base and inside this hook, I unset the id attribute.

my AccessToken model configuration file looks like this
```json
{
  "name": "accessToken",
  "base": "AccessToken",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "id": {
      "type": "string",
      "id": true,
      "mssql": {
        "dataType": "UniqueIdentifier"
      }
    },
    "ttl": {
      "type": "number",
      "default": 86400
    }
  },
  "validations": [],
  "relations": {
    "user": {
      "type": "belongsTo",
      "model": "user",
      "foreignKey": "userId"
    }
  },
  "acls": [],
  "methods": {}
}
```
Now whenever an accessToken gets generated, right before its saved, the id generated by loopback gets deleted, and instead, the SQL database generates a GUID that looks like this `BDABBA5F-D3CF-43F6-8188-F8A2862C1040` and it works perfectly.

**Comment by vedakp** [comment]
@jaideepdas you can change ID datatype to varchar(500). 
i changed my ID (pk,uniqueidenterfier) to id(varchar(500)) in database and its working fine now

**Comment by mjmgooch** [comment]
I have the same problem! Changing your column type to varchar(500) does work but doesnt feel like a proper fix. if it helps the code I used is below, you may get an error in relation to deleting a PK.

`ALTER TABLE AccessToken DROP COLUMN id
ALTER TABLE AccessToken ADD id nvarchar(500)`
