### ISSUE TITLE
mssql connector doesn't work on Azure

### ISSUE THREAD

**Issue by sochka** [strongloop/loopback-connector-mssql#67]
Hi, it seems like there is something problem with mssql connector on Azure. Even before the app boots, it crashes with the following error:

```
WARNING: LoopBack connector "mssql" is not installed as any of the following modules:

 ./connectors/mssql
loopback-connector-mssql

To fix, run:

    npm install loopback-connector-mssql
Application has thrown an uncaught exception and is terminated:
Error: 
WARNING: LoopBack connector "mssql" is not installed as any of the following modules:

 ./connectors/mssql
loopback-connector-mssql

To fix, run:

    npm install loopback-connector-mssql

    at DataSource.setup (D:\home\site\wwwroot\node_modules\loopback-datasource-juggler\lib\datasource.js:304:28)
    at new DataSource (D:\home\site\wwwroot\node_modules\loopback-datasource-juggler\lib\datasource.js:109:8)
    at Registry.createDataSource (D:\home\site\wwwroot\node_modules\loopback\lib\registry.js:349:12)
    at dataSourcesFromConfig (D:\home\site\wwwroot\node_modules\loopback\lib\application.js:415:19)
    at EventEmitter.app.dataSource (D:\home\site\wwwroot\node_modules\loopback\lib\application.js:222:12)
    at D:\home\site\wwwroot\node_modules\loopback-boot\lib\executor.js:169:9
    at D:\home\site\wwwroot\node_modules\loopback-boot\lib\executor.js:260:5
    at Array.forEach (native)
    at forEachKeyedObject (D:\home\site\wwwroot\node_modules\loopback-boot\lib\executor.js:259:20)
    at setupDataSources (D:\home\site\wwwroot\node_modules\loopback-boot\lib\executor.js:168:3)
```

On the other hand Postgres connector works flawlessly. I used Azure App Service (API app) for deployment. I checked the contents of the node_modules directory. Indeed, it had loopback-connector-mssql package inside. But loopback just fails to pick it up. It works locally, on the other hand. 

The only idea I have had is that relates to the fact that the app is launched using IISNode. But why doesn't Postgres connector crash as well?

**Comment by sochka** [comment]
@superkhau Hey, sorry for troubling you with this, maybe you know where is the location of the connector loader? The thing that would resolve the module name by concatenating 'loopback-connector-' with the connector name. I'd like to look at that place; maybe I'll find out what's going on. Also, do you know where is the license check? That could also be a problem since it somehow loads PostgreSQL connector but not mssql.

**Comment by superkhau** [comment]
>...maybe you know where is the location of the loader of connectors? The thing that would resolve the module name by concatenating 'loopback-connector-' with the connector name.

Is this what you're looking for? https://github.com/strongloop/loopback-datasource-juggler/blob/486c1de1ba4572f810606be1aa148db4d272e52c/lib/datasource.js#L196

>Also, do you know where is the license check? That could also be a problem since it somehow loads PostgreSQL connector but not mssql. 

I don't believe the postgres connector has a license check. You can see the example of a connector that does have one at https://github.com/strongloop/loopback-connector-oracle/blob/170654fc11931318e4d8591847e2f9b50b2a1f9e/index.js#L1.

**Comment by sochka** [comment]
This is really strange, I have no idea why that happens. Unfortunately this is blocking me with making a production build.

**Comment by sochka** [comment]
Hi, I just tested oracle's connector and it also doesn't seem to work:

```
Tue Jan 19 2016 13:37:06 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: 
WARNING: LoopBack connector "oracle" is not installed as any of the following modules:

 ./connectors/oracle
loopback-connector-oracle

To fix, run:

    npm install loopback-connector-oracle

    at DataSource.setup (D:\home\site\wwwroot\node_modules\loopback-datasource-juggler\lib\datasource.js:304:28)
    at new DataSource (D:\home\site\wwwroot\node_modules\loopback-datasource-juggler\lib\datasource.js:109:8)
    at Registry.createDataSource (D:\home\site\wwwroot\node_modules\loopback\lib\registry.js:349:12)
    at dataSourcesFromConfig (D:\home\site\wwwroot\node_modules\loopback\lib\application.js:415:19)
    at EventEmitter.app.dataSource (D:\home\site\wwwroot\node_modules\loopback\lib\application.js:222:12)
    at D:\home\site\wwwroot\node_modules\loopback-boot\lib\executor.js:169:9
    at D:\home\site\wwwroot\node_modules\loopback-boot\lib\executor.js:260:5
    at Array.forEach (native)
    at forEachKeyedObject (D:\home\site\wwwroot\node_modules\loopback-boot\lib\executor.js:259:20)
    at setupDataSources (D:\home\site\wwwroot\node_modules\loopback-boot\lib\executor.js:168:3)
```

**Comment by sochka** [comment]
Ok, I was finally able to deploy it, by adding this repo code as part of my own, and installing through npm's local dependency. But then, I spend about 5 hours debugging the problem with not being able to connect to the DB and as I learned after digging a few layers below, when using Azure, you have to add: `options: {encrypt: true}` to your config. Probably it's better to add this to the docs.
